services:
  editor:
    image: darpa-criticalmaas/ta2-minmod-editor
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MINMOD_API=https://dev.minmod.isi.edu
    ports:
      - "8888:80"